baseURL = "https://example.com"
title = "SkaDB"
theme = "hugo-myblog-theme"

defaultContentLanguage = "en"
#defaultContentLanguageInSubdir = true
hasCJKLanguage = false # Set to 'true' if want to use Chinese/Japanese/Korean

summaryLength = 70
#buildFuture = true # Debug purpose

copyright = "&copy;&nbsp;{year}"
#timeout = 10000 # Default: 10000 (10s)
enableEmoji = true
# TODO: seems like can't have this param defined in taxonomy code?
paginate = 12 # Default 10

#pluralizeListTitles = false
#enableGitInfo = false # Default: false
#googleAnalytics = "" # Default: ""

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true
      xHTML = true
  [markup.highlight]
    codeFences = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 1

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[languages]
  [languages.en]
    title = "Ska DB"
    languageName = "English"
    weight = 1
    contentdir = "content/en"
    [languages.en.params]
      languagedir = "ltr"
      languageShort = "EN"
